// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/vue-3/javascript/gantt-schedulerpro/src/App.vue
<!-- Application -->
<!-- Please note that this example uses the Bryntum Scheduler Pro, which is licensed separately. -->
<template>
    <div id="container">
        <bryntum-demo-header
            link="../../../../../#example-frameworks-vue-3-javascript-gantt-schedulerpro"
        >
            <bryntum-button
                icon="b-fa-search-plus"
                tooltip="Zoom In"
                cls="b-raised b-blue"
                @click="onZoom('In')"
            />
            <bryntum-button
                icon="b-fa-search-minus"
                tooltip="Zoom Out"
                cls="b-raised b-blue"
                @click="onZoom('Out')"
            />
        </bryntum-demo-header>

        <bryntum-gantt ref="gantt" v-bind="ganttConfig" />
        <bryntum-splitter />
        <bryntum-scheduler-pro ref="scheduler" v-bind="schedulerConfig" />
    </div>
</template>

<script>
import { onMounted, ref } from 'vue';
import {
    BryntumDemoHeader,
    BryntumGantt,
    BryntumSplitter,
    BryntumSchedulerPro,
    BryntumButton
} from "@bryntum/gantt-vue-3";
import { Toast } from '@bryntum/gantt';

import { ganttConfig, schedulerConfig } from "@/AppConfig";
export default {
    name: "App",

    components: {
        BryntumDemoHeader,
        BryntumGantt,
        BryntumSplitter,
        BryntumSchedulerPro,
        BryntumButton
    },

    setup() {

        const gantt = ref(null);
        const scheduler = ref(null)

        const onZoom = action => {
            gantt.value.instance.value[`zoom${action}`]();
        }

        onMounted(() => {
            scheduler.value.instance.value.addPartner(gantt.value.instance.value);

            Toast.show({
                timeout: 3000,
                html: 'Please note that this example uses the Bryntum Scheduler Pro, which is licensed separately.'
            });

        });

        return {
            ganttConfig,
            schedulerConfig,
            gantt,
            scheduler,
            onZoom
        }
    }
}
</script>

<style lang="scss">
@import "./App.scss";
</style>

// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/react/javascript/resource-histogram/src/App.js
/**
 * Application
 */
import React, { Fragment, useEffect, useRef } from 'react';

import {
    BryntumGantt,
    BryntumResourceHistogram,
    BryntumDemoHeader,
    BryntumThemeCombo,
    BryntumSplitter,
    BryntumButton
} from '@bryntum/gantt-react';

import './App.scss';
import { histogramConfig, ganttConfig } from './AppConfig';

function App() {
    const ganttRef = useRef(null);
    const histogramRef = useRef(null);

    // setup partnership between gantt and histogram
    useEffect(() => {
        histogramRef.current.instance.addPartner(ganttRef.current.instance);
    }, []);

    // Toolbar checkboxes click handler
    const onToolbarAction = (source) => {
        const action = source.dataset.action;
        histogramRef.current.instance[action] = source.checked;
    };

    // Zoom In/Out handler
    const onZoom = ({ source }) => {
        const {
            dataset: { action }
        } = source;
        ganttRef.current.instance[action]();
    };

    return (
        <Fragment>
            <BryntumDemoHeader
                href="../../../../../#example-frameworks-react-javascript-resource-histogram"
                children={<BryntumThemeCombo />}
            />
            <div className="demo-toolbar align-right" style={{ display: 'none' }}>
                <BryntumButton
                    dataset={{ action: 'zoomIn' }}
                    icon="b-icon-search-plus"
                    tooltip="Zoom in"
                    onAction={onZoom}
                />
                <BryntumButton
                    dataset={{ action: 'zoomOut' }}
                    icon="b-icon-search-minus"
                    tooltip="Zoom out"
                    onAction={onZoom}
                />
            </div>
            <BryntumGantt ref={ganttRef} {...ganttConfig} />
            <BryntumSplitter />
            <BryntumResourceHistogram
                ref={histogramRef}
                extraData={{ onToolbarAction }}
                {...histogramConfig}
            />
        </Fragment>
    );
}

export default App;
