// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/vue/javascript/taskeditor/src/App.vue
<!-- Application -->
<template>
    <div id="container">
        <bryntum-demo-header
            link="../../../../../#example-frameworks-vue-javascript-taskeditor"
        />
        <bryntum-gantt v-bind="ganttConfig" />
    </div>
</template>

<script>
import { ganttConfig } from "@/AppConfig";
import { BryntumDemoHeader, BryntumGantt } from "@bryntum/gantt-vue";

export default {
    name: "app",

    components: {
        BryntumDemoHeader,
        BryntumGantt,
    },

    data() {
        return { ganttConfig };
    },
};
</script>

<style lang="scss">
@import "./App.scss";
</style>

// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/react/javascript/taskeditor/src/App.js
/**
 * The App file. It should stay as simple as possible
 */

import React, { Fragment } from 'react';
import { BryntumDemoHeader, BryntumThemeCombo, BryntumGantt } from '@bryntum/gantt-react';
import { ganttConfig } from './AppConfig';
import './App.scss';

const App = () => {
    return (
        <Fragment>
            <BryntumDemoHeader
                href="../../../../../#example-frameworks-react-javascript-taskeditor"
                children={<BryntumThemeCombo />}
            />
            <BryntumGantt {...ganttConfig} />
        </Fragment>
    );
};

export default App;
