// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/react/javascript/basic/src/App.js
/**
 * Application
 */
import React, { Fragment } from 'react';

import { BryntumDemoHeader, BryntumThemeCombo, BryntumGantt } from '@bryntum/gantt-react';
import { ganttConfig } from './AppConfig';
import './App.scss';

const App = () => {
    // edit button click handler
    const handleEditClick = ({ record, grid: gantt }) => {
        gantt.editTask(record);
    };

    return (
        <Fragment>
            <BryntumDemoHeader
                href="../../../../../#example-frameworks-react-javascript-basic"
                children={<BryntumThemeCombo />}
            />
            <BryntumGantt {...ganttConfig} extraData={{ handleEditClick }} />
        </Fragment>
    );
};

export default App;

// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/vue/javascript/advanced/src/App.vue
<!--
* Vue Application Component
-->
<template>
    <div id="container">
        <bryntum-demo-header
            link="../../../../../#example-frameworks-vue-javascript-advanced"
        />
        <bryntum-gantt v-bind="ganttConfig" />
    </div>
</template>

<script>
import { BryntumDemoHeader, BryntumGantt } from "@bryntum/gantt-vue";
import { ganttConfig } from "@/AppConfig";

export default {
    name: "app",

    components: {
        BryntumDemoHeader,
        BryntumGantt
    },
    data() {
        return {
            ganttConfig
        };
    }
};
</script>

<style lang="scss">
@import "./App.scss";
</style>
