// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/vue/javascript/rollups/src/App.vue
<!-- Application -->
<template>
    <div id="container">
        <bryntum-demo-header
            link="../../../../../#example-frameworks-vue-javascript-rollups"
        />
        <div class="demo-toolbar align-right">
            <bryntum-checkbox
                :checked="true"
                text="Show Rollups"
                @change="onShowRollups"
            />
        </div>
        <bryntum-gantt ref="gantt" v-bind="ganttConfig" />
    </div>
</template>

<script>
import {
    BryntumDemoHeader,
    BryntumGantt,
    BryntumCheckbox,
} from "@bryntum/gantt-vue";
import { ganttConfig } from "@/AppConfig";

export default {
    name: "App",

    components: {
        BryntumDemoHeader,
        BryntumCheckbox,
        BryntumGantt,
    },

    methods: {
        onShowRollups({ checked }) {
            this.$refs.gantt.instance.features.rollups.disabled = !checked;
        },
    },

    data() {
        return { ganttConfig };
    },
};
</script>

<style lang="scss">
@import "./App.scss";
</style>

// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/react/javascript/rollups/src/App.js
/**
 * Application
 */

import React, { Fragment, useRef } from 'react';

import {
    BryntumDemoHeader,
    BryntumThemeCombo,
    BryntumGantt,
    BryntumCheckbox
} from '@bryntum/gantt-react';
import { ganttConfig } from './AppConfig';

import './App.scss';

const App = () => {
    const ganttRef = useRef(null);

    const onRollupsChange = ({ checked }) => {
        ganttRef.current.instance.features.rollups.disabled = !checked;
    };
    return (
        <Fragment>
            <BryntumDemoHeader
                href="../../../../../#example-frameworks-react-javascript-rollups"
                children={<BryntumThemeCombo />}
            />
            <div className="demo-toolbar">
                <BryntumCheckbox
                    label="Show Rollups"
                    checked={true}
                    onChange={onRollupsChange}
                />
            </div>
            <BryntumGantt ref={ganttRef} {...ganttConfig} />
        </Fragment>
    );
};

export default App;
