// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/angular/pdf-export/src/app/app.component.ts
import { Component, AfterViewInit, ViewChild } from '@angular/core';
import { BryntumGanttComponent } from '@bryntum/gantt-angular';
import { Gantt } from '@bryntum/gantt/gantt.lite.umd.js';
import ganttConfig from './app.config';

@Component({
    selector    : 'app-root',
    templateUrl : './app.component.html',
    styleUrls   : ['./app.component.scss']
})
export class AppComponent implements AfterViewInit {

    ganttConfig = ganttConfig;
    private gantt: Gantt;

    @ViewChild(BryntumGanttComponent, { static : false }) ganttComponent: BryntumGanttComponent;

    ngAfterViewInit(): void {
        // Store Gantt instance
        this.gantt = this.ganttComponent.instance;
    }

    onPdfExport(): void {
        this.gantt.features.pdfExport.showExportDialog();
    }

}

<bryntum-demo-header
    link = "../../../../../#example-frameworks-angular-pdf-export"
></bryntum-demo-header>

<div class = "demo-toolbar align-right">
    <bryntum-button
        cls = "b-skip-test b-deep-orange b-raised"
        text = "Export to PDF/PNG"
        (onClick) = "onPdfExport()"
    ></bryntum-button>
</div>

<bryntum-gantt
    #gantt
    [columns] = "ganttConfig.columns"
    [project] = "ganttConfig.project"
    [pdfExportFeature] = "ganttConfig.features.pdfExport"
></bryntum-gantt>

// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/vue/javascript/pdf-export/src/App.vue
<!--
 * Vue Application Component
 -->
<template>
    <div id="container">
        <bryntum-demo-header
            link="../../../../../#example-frameworks-vue-javascript-pdf-export"
        />
        <div class="demo-toolbar align-right">
            <bryntum-button
                cls="b-deep-orange b-raised"
                text="Export to PDF/PNG"
                @click="exportHandler"
            />
        </div>
        <bryntum-gantt
            ref="gantt"
            v-bind="ganttConfig"
        ></bryntum-gantt>
    </div>
</template>

<script>
import {
    BryntumGantt,
    BryntumDemoHeader,
    BryntumButton
} from '@bryntum/gantt-vue';
import { ganttConfig } from '@/AppConfig.js';

export default {
    name: 'app',

    // local components
    components: {
        BryntumDemoHeader,
        BryntumGantt,
        BryntumButton
    },

    data() {
        return {
            ganttConfig
        };
    },

    methods: {
        exportHandler() {
            this.$refs.gantt.instance.features.pdfExport.showExportDialog();
        }
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>
