// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/react/typescript/basic/src/App.tsx
/**
 * Main Application script
 */
import React, { Fragment, FunctionComponent } from 'react';

import { BryntumDemoHeader, BryntumThemeCombo, BryntumGantt } from '@bryntum/gantt-react';
import { ganttConfig } from './AppConfig';
import './App.scss';

const App: FunctionComponent = () => {
    return (
        <Fragment>
            <BryntumDemoHeader
                href="../../../../../#example-frameworks-react-typescript-basic"
                children={<BryntumThemeCombo />}
            />
            <BryntumGantt {...ganttConfig} />
        </Fragment>
    );
};

export default App;

// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/vue/javascript/vue-renderer/src/App.vue
<!-- Application -->
<template>
    <div id="container">
        <bryntum-demo-header
            link="../../../../../#example-frameworks-vue-javascript-vue-renderer"
        ></bryntum-demo-header>
        <bryntum-gantt v-bind="ganttConfig" />
    </div>
</template>

<script>
import { BryntumDemoHeader, BryntumGantt } from '@bryntum/gantt-vue';
import { ganttConfig } from '@/AppConfig';

export default {
    name: 'App',

    components: {
        BryntumGantt,
        BryntumDemoHeader
    },

    data() {
        return { ganttConfig };
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>
