// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/react/javascript/timeranges/src/App.js
/**
 * The App file. It should stay as simple as possible
 */

import React, { Fragment, useEffect, useRef } from 'react';
import {
    BryntumDemoHeader,
    BryntumThemeCombo,
    BryntumGantt,
    BryntumSplitter,
    BryntumGrid
} from '@bryntum/gantt-react';
import { Toast } from '@bryntum/gantt';
import { ganttConfig, gridConfig } from './AppConfig';
import './App.scss';

const App = () => {
    const ganttRef = useRef(null);
    const gridRef = useRef(null);

    // set grid store to timeRanges store
    useEffect(() => {
        gridRef.current.instance.store = ganttRef.current.instance.features.timeRanges.store;
        Toast.show({
            timeout: 3000,
            html:
                'Please note that this example uses the Bryntum Grid, which is licensed separately.'
        });
    }, []);

    // Add time range button click handler
    const addTimeRange = () => {
        gridRef.current.instance.store.add({
            name: 'New range',
            startDate: new Date(2019, 0, 10),
            duration: 5
        });
    };

    // Toggle Show headers handler
    const toggleShowHeaders = ({ source }) => {
        ganttRef.current.instance.features.timeRanges.showHeaderElements = source.pressed;
    };

    return (
        <Fragment>
            <BryntumDemoHeader
                href="../../../../../#example-frameworks-react-javascript-timeranges"
                children={<BryntumThemeCombo />}
            />
            <div id="content">
                <BryntumGantt
                    ref={ganttRef}
                    {...ganttConfig}
                    bbar={{
                        cls: 'gantt-bbar',
                        items: [
                            {
                                toggleable: true,
                                text: 'Show header elements',
                                tooltip: 'Toggles the rendering of time range header elements',
                                pressed: true,
                                icon: 'b-fa-square',
                                pressedIcon: 'b-fa-check-square',
                                onClick: toggleShowHeaders
                            }
                        ]
                    }}
                />
                <BryntumSplitter />
                <BryntumGrid
                    ref={gridRef}
                    {...gridConfig}
                    bbar={[
                        {
                            text: 'Add time range',
                            icon: 'b-fa-plus',
                            cls: 'b-green',
                            onClick: addTimeRange
                        }
                    ]}
                />
            </div>
        </Fragment>
    );
};

export default App;

// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/angular/timeranges/src/app/app.component.ts
/**
 * App component script
 */
import { AfterViewInit, Component, ViewChild } from '@angular/core';
import { BryntumGanttComponent, BryntumGridComponent, BryntumSplitterComponent } from '@bryntum/gantt-angular';
import { Gantt, GanttConfig, Grid, GridConfig, Store } from '@bryntum/gantt/gantt.lite.umd.js';
import { ganttConfig, gridConfig } from './app.config';

@Component({
    selector    : 'app-root',
    templateUrl : './app.component.html',
    styleUrls   : ['./app.component.scss']
})
export class AppComponent implements AfterViewInit {
    title: string = document.title;
    ganttConfig: Partial<GanttConfig> = ganttConfig;
    gridConfig: Partial<GridConfig> = gridConfig;

    private gantt: Gantt;
    private grid: Grid;
    private timeRangeStore: Store;

    @ViewChild(BryntumGanttComponent, { static : false }) ganttComponent: BryntumGanttComponent;
    @ViewChild(BryntumGridComponent, { static : false }) gridComponent: BryntumGridComponent;
    @ViewChild(BryntumSplitterComponent, { static : false }) splitterComponent: BryntumSplitterComponent;

    ngAfterViewInit(): void {
        // Store instance
        this.gantt = this.ganttComponent.instance;
        this.grid = this.gridComponent.instance;
        this.timeRangeStore = this.gantt.features.timeRanges.store;
        this.grid.store = this.timeRangeStore;
    }

    onAddRange(): void {
        this.timeRangeStore.add({
            name      : 'New range',
            startDate : new Date(2019, 1, 27),
            duration  : 5
        });
    }

    onShowHeaders({ checked }: any): void {
        this.gantt.features.timeRanges.showHeaderElements = checked;
    }
}

<bryntum-demo-header
    link = "../../../../../#example-frameworks-angular-timeranges"
></bryntum-demo-header>

<div class = "demo-toolbar align-right">
    <bryntum-checkbox
        text = "Show Gantt header elements"
        tooltip = "Toggles the rendering of time range header elements"
        checked = true
        cls = "b-blue"
        (onAction) = "onShowHeaders($event)"
    ></bryntum-checkbox>
</div>

<div id = "container">
    <bryntum-gantt
        #ganttComponent
        flex = 1
        [project] = "ganttConfig.project"
        [columns] = "ganttConfig.columns"
        [timeRangesFeature] = "ganttConfig.features.timeRanges"
    ></bryntum-gantt>
    <bryntum-splitter
        #splitter
    ></bryntum-splitter>
    <div class = "time-range-grid">
        <bryntum-grid
            #gridComponent
            flex = 1
            [columns] = "gridConfig.columns"
            [stripeFeature] = "gridConfig.features.stripe"
            [sortFeature] = "gridConfig.features.sort"
            cls="grid-timeranges"
        ></bryntum-grid>
        <div class = "demo-toolbar">
            <bryntum-button
                text = "Add"
                icon = "b-fa-plus"
                cls = "b-green"
                tooltip = "Add new time range"
                (onAction) = "onAddRange()"
            ></bryntum-button>
        </div>
    </div>
</div>
