// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/react/javascript/gantt-schedulerpro/src/App.js
/**
 * Application
 *
 * Please note that this example uses the Bryntum Scheduler Pro, which is licensed separately.
 */

import React, { useEffect, useRef } from 'react';

import {
    BryntumDemoHeader,
    BryntumThemeCombo,
    BryntumGantt,
    BryntumSchedulerPro,
    BryntumSplitter,
    BryntumButton
} from '@bryntum/gantt-react';
import { Toast } from '@bryntum/gantt';

import { ganttConfig, schedulerConfig } from './AppConfig';
import './App.scss';

const App = () => {

    const ganttRef = useRef();
    const schedulerRef = useRef();

    useEffect(()=> {
        schedulerRef.current.instance.addPartner(ganttRef.current.instance);

        Toast.show({
            timeout: 3000,
            html: 'Please note that this example uses the Bryntum Scheduler Pro, which is licensed separately.'
        });

    },[]);

    // ZoomIn/ZoomOut handler
    const zoom = action => {
        ganttRef.current.instance[`zoom${action}`]();
    }

    return (
        <>
            <BryntumDemoHeader
                href="../../../../../#example-frameworks-react-javascript-gantt-schedulerpro"
                children={
                    <>
                        <BryntumButton
                            icon="b-icon-search-plus"
                            cls="b-raised b-blue"
                            tooltip="Zoom In"
                            onClick={() => zoom('In')}
                        />
                        <BryntumButton
                            icon="b-icon-search-minus"
                            cls="b-raised b-blue"
                            tooltip="Zoom Out"
                            onClick={() => zoom('Out')}
                        />
                        <BryntumThemeCombo />
                    </>
                }
            />
            <div style={{
                display:'flex',
                flexDirection:'column',
                flex:1
            }}>
                <BryntumGantt {...ganttConfig} ref={ganttRef}/>
                <BryntumSplitter />
                {/* Please note that this example uses the Bryntum Scheduler Pro, which is licensed separately. */}
                <BryntumSchedulerPro {...schedulerConfig} ref={schedulerRef}/>
            </div>
        </>
    );
};

export default App;

// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/vue-3/javascript/gantt-schedulerpro/src/App.vue
<!-- Application -->
<!-- Please note that this example uses the Bryntum Scheduler Pro, which is licensed separately. -->
<template>
    <div id="container">
        <bryntum-demo-header
            link="../../../../../#example-frameworks-vue-3-javascript-gantt-schedulerpro"
        >
            <bryntum-button
                icon="b-fa-search-plus"
                tooltip="Zoom In"
                cls="b-raised b-blue"
                @click="onZoom('In')"
            />
            <bryntum-button
                icon="b-fa-search-minus"
                tooltip="Zoom Out"
                cls="b-raised b-blue"
                @click="onZoom('Out')"
            />
        </bryntum-demo-header>

        <bryntum-gantt ref="gantt" v-bind="ganttConfig" />
        <bryntum-splitter />
        <bryntum-scheduler-pro ref="scheduler" v-bind="schedulerConfig" />
    </div>
</template>

<script>
import { onMounted, ref } from 'vue';
import {
    BryntumDemoHeader,
    BryntumGantt,
    BryntumSplitter,
    BryntumSchedulerPro,
    BryntumButton
} from "@bryntum/gantt-vue-3";
import { Toast } from '@bryntum/gantt';

import { ganttConfig, schedulerConfig } from "@/AppConfig";
export default {
    name: "App",

    components: {
        BryntumDemoHeader,
        BryntumGantt,
        BryntumSplitter,
        BryntumSchedulerPro,
        BryntumButton
    },

    setup() {

        const gantt = ref(null);
        const scheduler = ref(null)

        const onZoom = action => {
            gantt.value.instance.value[`zoom${action}`]();
        }

        onMounted(() => {
            scheduler.value.instance.value.addPartner(gantt.value.instance.value);

            Toast.show({
                timeout: 3000,
                html: 'Please note that this example uses the Bryntum Scheduler Pro, which is licensed separately.'
            });

        });

        return {
            ganttConfig,
            schedulerConfig,
            gantt,
            scheduler,
            onZoom
        }
    }
}
</script>

<style lang="scss">
@import "./App.scss";
</style>
