// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/react/javascript/timeranges/src/App.js
/**
 * The App file. It should stay as simple as possible
 */

import React, { Fragment, useEffect, useRef } from 'react';
import {
    BryntumDemoHeader,
    BryntumThemeCombo,
    BryntumGantt,
    BryntumSplitter,
    BryntumGrid
} from '@bryntum/gantt-react';
import { Toast } from '@bryntum/gantt';
import { ganttConfig, gridConfig } from './AppConfig';
import './App.scss';

const App = () => {
    const ganttRef = useRef(null);
    const gridRef = useRef(null);

    // set grid store to timeRanges store
    useEffect(() => {
        gridRef.current.instance.store = ganttRef.current.instance.features.timeRanges.store;
        Toast.show({
            timeout: 3000,
            html:
                'Please note that this example uses the Bryntum Grid, which is licensed separately.'
        });
    }, []);

    // Add time range button click handler
    const addTimeRange = () => {
        gridRef.current.instance.store.add({
            name: 'New range',
            startDate: new Date(2019, 0, 10),
            duration: 5
        });
    };

    // Toggle Show headers handler
    const toggleShowHeaders = ({ source }) => {
        ganttRef.current.instance.features.timeRanges.showHeaderElements = source.pressed;
    };

    return (
        <Fragment>
            <BryntumDemoHeader
                href="../../../../../#example-frameworks-react-javascript-timeranges"
                children={<BryntumThemeCombo />}
            />
            <div id="content">
                <BryntumGantt
                    ref={ganttRef}
                    {...ganttConfig}
                    bbar={{
                        cls: 'gantt-bbar',
                        items: [
                            {
                                toggleable: true,
                                text: 'Show header elements',
                                tooltip: 'Toggles the rendering of time range header elements',
                                pressed: true,
                                icon: 'b-fa-square',
                                pressedIcon: 'b-fa-check-square',
                                onClick: toggleShowHeaders
                            }
                        ]
                    }}
                />
                <BryntumSplitter />
                <BryntumGrid
                    ref={gridRef}
                    {...gridConfig}
                    bbar={[
                        {
                            text: 'Add time range',
                            icon: 'b-fa-plus',
                            cls: 'b-green',
                            onClick: addTimeRange
                        }
                    ]}
                />
            </div>
        </Fragment>
    );
};

export default App;

// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/vue-3/javascript/gantt-schedulerpro/src/App.vue
<!-- Application -->
<!-- Please note that this example uses the Bryntum Scheduler Pro, which is licensed separately. -->
<template>
    <div id="container">
        <bryntum-demo-header
            link="../../../../../#example-frameworks-vue-3-javascript-gantt-schedulerpro"
        >
            <bryntum-button
                icon="b-fa-search-plus"
                tooltip="Zoom In"
                cls="b-raised b-blue"
                @click="onZoom('In')"
            />
            <bryntum-button
                icon="b-fa-search-minus"
                tooltip="Zoom Out"
                cls="b-raised b-blue"
                @click="onZoom('Out')"
            />
        </bryntum-demo-header>

        <bryntum-gantt ref="gantt" v-bind="ganttConfig" />
        <bryntum-splitter />
        <bryntum-scheduler-pro ref="scheduler" v-bind="schedulerConfig" />
    </div>
</template>

<script>
import { onMounted, ref } from 'vue';
import {
    BryntumDemoHeader,
    BryntumGantt,
    BryntumSplitter,
    BryntumSchedulerPro,
    BryntumButton
} from "@bryntum/gantt-vue-3";
import { Toast } from '@bryntum/gantt';

import { ganttConfig, schedulerConfig } from "@/AppConfig";
export default {
    name: "App",

    components: {
        BryntumDemoHeader,
        BryntumGantt,
        BryntumSplitter,
        BryntumSchedulerPro,
        BryntumButton
    },

    setup() {

        const gantt = ref(null);
        const scheduler = ref(null)

        const onZoom = action => {
            gantt.value.instance.value[`zoom${action}`]();
        }

        onMounted(() => {
            scheduler.value.instance.value.addPartner(gantt.value.instance.value);

            Toast.show({
                timeout: 3000,
                html: 'Please note that this example uses the Bryntum Scheduler Pro, which is licensed separately.'
            });

        });

        return {
            ganttConfig,
            schedulerConfig,
            gantt,
            scheduler,
            onZoom
        }
    }
}
</script>

<style lang="scss">
@import "./App.scss";
</style>
