// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/angular/rollups/src/app/app.component.ts
/**
 * App component script
 */
import { AfterViewInit, Component, ViewChild } from '@angular/core';
import { BryntumGanttComponent } from '@bryntum/gantt-angular';
import { Gantt } from '@bryntum/gantt/gantt.lite.umd.js';
import ganttConfig from './app.config';

@Component({
    selector    : 'app-root',
    templateUrl : './app.component.html',
    styleUrls   : ['./app.component.scss']
})
export class AppComponent implements AfterViewInit {

    ganttConfig = ganttConfig;
    private gantt: Gantt;

    @ViewChild(BryntumGanttComponent, { static : false }) ganttComponent: BryntumGanttComponent;

    ngAfterViewInit(): void {
        // Store Gantt instance
        this.gantt = this.ganttComponent.instance;
    }

    onShowRollups(event: any): void {
        if (event.type === 'action') {
            this.gantt.features.rollups.disabled = !event.source.checked;
        }
    }

}

<bryntum-demo-header
    link = "../../../../../#example-frameworks-angular-rollups"
></bryntum-demo-header>

<div class = "demo-toolbar align-right">
    <bryntum-checkbox
        text = 'Show Rollups'
        tooltip = 'Toggle rollups showing'
        checked = true
        cls = 'b-blue'
        (onAction) = "onShowRollups($event)"
    ></bryntum-checkbox>
</div>

<bryntum-gantt
    #gantt
    [barMargin] = "ganttConfig.barMargin"
    [columnLines] = "ganttConfig.columnLines"
    [columns] = "ganttConfig.columns"
    [project] = "ganttConfig.project"
    [rollupsFeature] = "ganttConfig.features.rollups"
    [rowHeight] = "ganttConfig.rowHeight"
    [subGridConfigs] = "ganttConfig.subGridConfigs"
    [viewPreset] = "ganttConfig.viewPreset"
></bryntum-gantt>

// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/vue/javascript/rollups/src/App.vue
<!-- Application -->
<template>
    <div id="container">
        <bryntum-demo-header
            link="../../../../../#example-frameworks-vue-javascript-rollups"
        />
        <div class="demo-toolbar align-right">
            <bryntum-checkbox
                :checked="true"
                text="Show Rollups"
                @change="onShowRollups"
            />
        </div>
        <bryntum-gantt ref="gantt" v-bind="ganttConfig" />
    </div>
</template>

<script>
import {
    BryntumDemoHeader,
    BryntumGantt,
    BryntumCheckbox,
} from "@bryntum/gantt-vue";
import { ganttConfig } from "@/AppConfig";

export default {
    name: "App",

    components: {
        BryntumDemoHeader,
        BryntumCheckbox,
        BryntumGantt,
    },

    methods: {
        onShowRollups({ checked }) {
            this.$refs.gantt.instance.features.rollups.disabled = !checked;
        },
    },

    data() {
        return { ganttConfig };
    },
};
</script>

<style lang="scss">
@import "./App.scss";
</style>
