// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/vue/javascript/advanced/src/App.vue
<!--
* Vue Application Component
-->
<template>
    <div id="container">
        <bryntum-demo-header
            link="../../../../../#example-frameworks-vue-javascript-advanced"
        />
        <bryntum-gantt v-bind="ganttConfig" />
    </div>
</template>

<script>
import { BryntumDemoHeader, BryntumGantt } from "@bryntum/gantt-vue";
import { ganttConfig } from "@/AppConfig";

export default {
    name: "app",

    components: {
        BryntumDemoHeader,
        BryntumGantt
    },
    data() {
        return {
            ganttConfig
        };
    }
};
</script>

<style lang="scss">
@import "./App.scss";
</style>

// src/main/webapp/gantt-5.0.1-trial/examples/frameworks/angular/advanced/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
    selector    : 'app-root',
    templateUrl : './app.component.html',
    styleUrls   : ['./app.component.scss']
})
export class AppComponent {
}

<bryntum-demo-header
    link  = "../../../../../#example-frameworks-angular-advanced"
></bryntum-demo-header>

<app-gantt></app-gantt>
